### ISSUE TITLE
WhomとWhoの区別ができていない

### ISSUE THREAD

**Issue by koujikozaki** [KnowledgeGraphJapan/Challenge#12]
TSVからRDF化する際に、WhoとWhomの両方がsubjectに変換されている。
Whomはwhomとして残すべき。

**Comment by e4028710** [comment]
踊る人形144がこれに該当する

**Comment by koujikozaki** [comment]
プログラムは修正済み

**Comment by koujikozaki** [comment]
対応したものを下記で公開
https://github.com/KnowledgeGraphJapan/KGRC-RDF/tree/master/2019
