### ISSUE TITLE
踊る人形1 beDrawn が drawnになっている(ttl)

### ISSUE THREAD

**Issue by e4028710** [KnowledgeGraphJapan/Challenge#16]
ID:1,8など
ID: 122のbeMovedもmovedになっている

**Comment by koujikozaki** [comment]
be○○は「状態の変化」を伴う時にhasPredicateにおいて使い，
「描かれていた」のように，その状態になっている場合は，
「hasProperty＋beを付けない」という方針となったため，drawnに統一しています．

**Comment by e4028710** [comment]
了解しました．
