### ISSUE TITLE
ACaseOfIdentity.ttlの英語接続詞1語から成るシーンは誤り？（シーン059, 061, 246, 251, 320, 338など）

### ISSUE THREAD

**Issue by siramatu** [KnowledgeGraphJapan/Challenge#6]
他にもありそうです。
&lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/059>
    rdf:type    kgc:Situation;
    kgc:source  "if"@ja ;
    kgc:source  "if"@en ;
    kgc:hasPredicate   &lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/if>.

&lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/061>
    rdf:type    kgc:Situation;
    kgc:source  "then"@ja ;
    kgc:source  "then"@en ;
    kgc:hasPredicate   &lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/then>.

&lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/246>
    rdf:type    kgc:Situation;
    kgc:source  "if"@ja ;
    kgc:source  "if"@en ;
    kgc:hasPredicate   &lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/if>.

&lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/251>
    rdf:type    kgc:Situation;
    kgc:source  "therefore"@ja ;
    kgc:source  "thereore"@en ;
    kgc:hasPredicate   &lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/thereore>.

&lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/320>
    rdf:type    kgc:Situation;
    kgc:source  "then"@ja ;
    kgc:source  "then"@en ;
    kgc:hasPredicate   &lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/then>.

&lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/338>
    rdf:type    kgc:Situation;
    kgc:source  "therefore"@ja ;
    kgc:source  "thereore"@en ;
    kgc:hasPredicate   &lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/thereore>.

&lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/344>
    rdf:type    kgc:Situation;
    kgc:source  "therefore"@ja ;
    kgc:source  "thereore"@en ;
    kgc:hasPredicate   &lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/thereore>.

&lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/347>
    rdf:type    kgc:Situation;
    kgc:source  "therefore"@ja ;
    kgc:source  "thereore"@en ;
    kgc:hasPredicate   &lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/thereore>.

&lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/384>
    rdf:type    kgc:Situation;
    kgc:source  "if"@ja ;
    kgc:source  "if"@en ;
    kgc:hasPredicate   &lt;http://kgc.knowledge-graph.jp/data/ACaseOfIdentity/if>.

**Comment by koujikozaki** [comment]
RDFへの変換時にミスがあったようです．
現在作業中の修正版では，この点も修正しますので，少々お待ちください．

**Comment by takanori-ugai** [comment]
ご指摘ありがとうございます。現在公開している版では修正されています。

**Comment by koujikozaki** [comment]
この問題自体は解決したが，副次的なもんだいがあり
https://github.com/KnowledgeGraphJapan/KGRC-RDF/issues/2
参照
