### ISSUE TITLE
踊る人形88 whatのidが分割されていない(ttl)

### ISSUE THREAD

**Issue by yayamamo** [KnowledgeGraphJapan/Challenge#9]
以下のWhatの目的語はそれぞれ、kgc:Statementの089, 090, 091へのリンクと思われますがうまくデータが生成されていないようです。

|Predicate | Object|
|-- | --|
|rdf:type | Situation|
|source | "地元の医者が以下を言った"|
|source | "A local doctor say the followings"|
|hasPredicate | say|
|what | 89,_90,_91|
|subject | Local_doctor|
|time | "1903-08-06T14:00:00"|

**Comment by e4028710** [comment]
踊る人形 ID:173のbecauseも分割されていない

**Comment by koujikozaki** [comment]
変換プログラム対応済み．
踊る人形の173については，abcで枝番を付けているので，判定メソッドにて仮対応

**Comment by koujikozaki** [comment]
対応したものを下記で公開
https://github.com/KnowledgeGraphJapan/KGRC-RDF/tree/master/2019
